# Generated by Django 5.0.5 on 2024-05-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_alter_currency_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(choices=[('CHF', ' Swiss franc'), ('AUD', 'Australian dollar'), ('USD', 'United States dollar'), ('GBP', 'British pound sterling'), ('CAD', 'Canadian dollar'), ('JPY', 'Japanese yen'), ('EUR', 'Euro')], max_length=255, unique=True),
        ),
    ]
