# Generated by Django 5.0.5 on 2024-05-08 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_alter_currency_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(choices=[('USD', 'United States dollar'), ('JPY', 'Japanese yen'), ('CHF', ' Swiss franc'), ('CAD', 'Canadian dollar'), ('EUR', 'Euro'), ('GBP', 'British pound sterling'), ('AUD', 'Australian dollar')], max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='bank.currency'),
        ),
    ]
