# Generated by Django 5.0.6 on 2024-05-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_alter_currency_code_alter_wallet_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(choices=[('JPY', 'Japanese yen'), ('EUR', 'Euro'), ('USD', 'United States dollar'), ('GBP', 'British pound sterling'), ('CHF', ' Swiss franc'), ('CAD', 'Canadian dollar'), ('AUD', 'Australian dollar')], max_length=255, unique=True),
        ),
    ]
