# Generated by Django 5.0.6 on 2024-05-13 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_alter_currency_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(choices=[('AUD', 'Australian dollar'), ('USD', 'United States dollar'), ('CAD', 'Canadian dollar'), ('GBP', 'British pound sterling'), ('EUR', 'Euro'), ('CHF', ' Swiss franc'), ('JPY', 'Japanese yen')], max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='currency', to='bank.currency'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_receiver', to='bank.customer'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_sender', to='bank.customer'),
        ),
    ]
