# Generated by Django 5.0.6 on 2024-05-20 08:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_alter_currency_code_alter_customeravatar_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(choices=[('JPY', 'Japanese yen'), ('EUR', 'Euro'), ('CAD', 'Canadian dollar'), ('CHF', ' Swiss franc'), ('GBP', 'British pound sterling'), ('USD', 'United States dollar'), ('AUD', 'Australian dollar')], max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='customeravatar',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to='bank.customer'),
        ),
    ]
